# Generated by Django 5.2 on 2025-06-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('type', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('pkmn_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pkmn_name', models.CharField(max_length=32, unique=True)),
                ('pkmn_height', models.FloatField()),
                ('pkmn_weight', models.FloatField()),
                ('pkmn_desc', models.CharField(max_length=255)),
                ('pkmn_type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type1', to='pokedex.type')),
                ('pkmn_type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type2', to='pokedex.type')),
            ],
        ),
    ]
