# Generated by Django 5.2 on 2025-07-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_pkmn_sprite_pokemon_pkmn_sprite_shiny_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pkmn_sprite',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pkmn_sprite_shiny',
        ),
    ]
