# Generated by Django 5.2 on 2025-07-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_remove_pokemon_pkmn_sprite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(null=True),
        ),
    ]
